// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagementSystem.Data;

#nullable disable

namespace ProjectManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<int?>("AdminActivityLogId")
                        .HasColumnType("int");

                    b.Property<bool>("BlocksSubmissions")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("AdminActivityLogId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.AcademicYear", b =>
                {
                    b.Property<int>("AcademicYear_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcademicYear_pkId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("YearRange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AcademicYear_pkId");

                    b.ToTable("AcademicYears");

                    b.HasData(
                        new
                        {
                            AcademicYear_pkId = 2025,
                            IsActive = true,
                            YearRange = "2024-2025"
                        },
                        new
                        {
                            AcademicYear_pkId = 2024,
                            IsActive = true,
                            YearRange = "2023-2024"
                        },
                        new
                        {
                            AcademicYear_pkId = 2023,
                            IsActive = true,
                            YearRange = "2022-2023"
                        },
                        new
                        {
                            AcademicYear_pkId = 2022,
                            IsActive = true,
                            YearRange = "2021-2022"
                        },
                        new
                        {
                            AcademicYear_pkId = 2021,
                            IsActive = true,
                            YearRange = "2020-2021"
                        },
                        new
                        {
                            AcademicYear_pkId = 2020,
                            IsActive = true,
                            YearRange = "2019-2020"
                        },
                        new
                        {
                            AcademicYear_pkId = 2019,
                            IsActive = true,
                            YearRange = "2018-2019"
                        },
                        new
                        {
                            AcademicYear_pkId = 2018,
                            IsActive = true,
                            YearRange = "2017-2018"
                        },
                        new
                        {
                            AcademicYear_pkId = 2017,
                            IsActive = true,
                            YearRange = "2016-2017"
                        },
                        new
                        {
                            AcademicYear_pkId = 2016,
                            IsActive = true,
                            YearRange = "2015-2016"
                        },
                        new
                        {
                            AcademicYear_pkId = 2015,
                            IsActive = true,
                            YearRange = "2014-2015"
                        },
                        new
                        {
                            AcademicYear_pkId = 2014,
                            IsActive = true,
                            YearRange = "2013-2014"
                        },
                        new
                        {
                            AcademicYear_pkId = 2013,
                            IsActive = true,
                            YearRange = "2012-2013"
                        },
                        new
                        {
                            AcademicYear_pkId = 2012,
                            IsActive = true,
                            YearRange = "2011-2012"
                        },
                        new
                        {
                            AcademicYear_pkId = 2011,
                            IsActive = true,
                            YearRange = "2010-2011"
                        },
                        new
                        {
                            AcademicYear_pkId = 2010,
                            IsActive = true,
                            YearRange = "2009-2010"
                        },
                        new
                        {
                            AcademicYear_pkId = 2009,
                            IsActive = true,
                            YearRange = "2008-2009"
                        },
                        new
                        {
                            AcademicYear_pkId = 2008,
                            IsActive = true,
                            YearRange = "2007-2008"
                        },
                        new
                        {
                            AcademicYear_pkId = 2007,
                            IsActive = true,
                            YearRange = "2006-2007"
                        },
                        new
                        {
                            AcademicYear_pkId = 2006,
                            IsActive = true,
                            YearRange = "2005-2006"
                        },
                        new
                        {
                            AcademicYear_pkId = 2005,
                            IsActive = true,
                            YearRange = "2004-2005"
                        },
                        new
                        {
                            AcademicYear_pkId = 2004,
                            IsActive = true,
                            YearRange = "2003-2004"
                        },
                        new
                        {
                            AcademicYear_pkId = 2003,
                            IsActive = true,
                            YearRange = "2002-2003"
                        },
                        new
                        {
                            AcademicYear_pkId = 2002,
                            IsActive = true,
                            YearRange = "2001-2002"
                        },
                        new
                        {
                            AcademicYear_pkId = 2001,
                            IsActive = true,
                            YearRange = "2000-2001"
                        },
                        new
                        {
                            AcademicYear_pkId = 2000,
                            IsActive = true,
                            YearRange = "1999-2000"
                        });
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.AdminActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoggedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AdminActivityLog");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsUsingDefaultPassword")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.AuditLog", b =>
                {
                    b.Property<int>("Log_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Log_pkId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Student_pkId")
                        .HasColumnType("int");

                    b.HasKey("Log_pkId");

                    b.HasIndex("Student_pkId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.City", b =>
                {
                    b.Property<int>("City_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("City_pkId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("City_pkId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Company", b =>
                {
                    b.Property<int>("Company_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Company_pkId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("City_pkId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contact")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Company_pkId");

                    b.HasIndex("City_pkId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Email", b =>
                {
                    b.Property<int>("Email_PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Email_PkId"));

                    b.Property<int?>("AcademicYear_pkId")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Email_PkId");

                    b.HasIndex("AcademicYear_pkId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Framework", b =>
                {
                    b.Property<int>("Framework_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Framework_pkId"));

                    b.Property<string>("FrameworkName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Language_pkId")
                        .HasColumnType("int");

                    b.HasKey("Framework_pkId");

                    b.HasIndex("Language_pkId");

                    b.ToTable("Frameworks");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Language", b =>
                {
                    b.Property<int>("Language_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Language_pkId"));

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectType_pkId")
                        .HasColumnType("int");

                    b.HasKey("Language_pkId");

                    b.HasIndex("ProjectType_pkId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.NRCTownship", b =>
                {
                    b.Property<int>("NRC_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NRC_pkId"));

                    b.Property<string>("RegionCode_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCode_M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TownshipCode_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TownshipCode_M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TownshipName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NRC_pkId");

                    b.ToTable("NRCTownships");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.NRCType", b =>
                {
                    b.Property<int>("NRCType_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NRCType_pkId"));

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NRCType_pkId");

                    b.ToTable("NRCTypes");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Notification", b =>
                {
                    b.Property<int>("Notification_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Notification_pkId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Project_pkId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Notification_pkId");

                    b.HasIndex("Project_pkId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.OTP", b =>
                {
                    b.Property<int>("OTP_PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OTP_PkId"));

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OTPCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("datetime2");

                    b.HasKey("OTP_PkId");

                    b.ToTable("OTPs");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Project", b =>
                {
                    b.Property<int>("Project_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Project_pkId"));

                    b.Property<string>("AdminComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Company_pkId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("Framework_pkId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApprovedByTeacher")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Language_pkId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ProjectSubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProjectType_pkId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SubmittedByStudent_pkId")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Project_pkId");

                    b.HasIndex("Company_pkId");

                    b.HasIndex("Framework_pkId");

                    b.HasIndex("Language_pkId");

                    b.HasIndex("ProjectType_pkId");

                    b.HasIndex("SubmittedByStudent_pkId")
                        .IsUnique()
                        .HasFilter("[SubmittedByStudent_pkId] IS NOT NULL");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.ProjectFile", b =>
                {
                    b.Property<int>("ProjectFile_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectFile_pkId"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Project_pkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectFile_pkId");

                    b.HasIndex("Project_pkId");

                    b.ToTable("ProjectFiles");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.ProjectMember", b =>
                {
                    b.Property<int?>("Project_pkId")
                        .HasColumnType("int");

                    b.Property<int?>("Student_pkId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectMember_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectMember_pkId"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Project_pkId", "Student_pkId");

                    b.HasIndex("Student_pkId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.ProjectType", b =>
                {
                    b.Property<int>("ProjectType_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectType_pkId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProjectType_pkId");

                    b.ToTable("ProjectTypes");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Student", b =>
                {
                    b.Property<int>("Student_pkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_pkId"));

                    b.Property<int>("AcademicYear_pkId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Department_pkID")
                        .HasColumnType("int");

                    b.Property<int?>("Email_PkId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NRCNumber")
                        .HasColumnType("int");

                    b.Property<int>("NRCType_pkId")
                        .HasColumnType("int");

                    b.Property<int?>("NRC_pkId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Student_pkId");

                    b.HasIndex("AcademicYear_pkId");

                    b.HasIndex("Department_pkID");

                    b.HasIndex("Email_PkId");

                    b.HasIndex("NRCType_pkId");

                    b.HasIndex("NRC_pkId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.StudentDepartment", b =>
                {
                    b.Property<int>("Department_pkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Department_pkID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Department_pkID");

                    b.ToTable("StudentDepartments");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.SuccessStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternshipCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SuccessStories");
                });

            modelBuilder.Entity("Announcement", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.AdminActivityLog", "Admin")
                        .WithMany("Announcements")
                        .HasForeignKey("AdminActivityLogId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.AuditLog", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("Student_pkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Company", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.City", "City")
                        .WithMany("Companies")
                        .HasForeignKey("City_pkId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Email", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYear_pkId");

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Framework", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.Language", "Language")
                        .WithMany("Frameworks")
                        .HasForeignKey("Language_pkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Language", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.ProjectType", "ProjectType")
                        .WithMany("Languages")
                        .HasForeignKey("ProjectType_pkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Notification", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("Project_pkId");

                    b.HasOne("ProjectManagementSystem.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Project", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_pkId");

                    b.HasOne("ProjectManagementSystem.Models.Framework", "Framework")
                        .WithMany("Projects")
                        .HasForeignKey("Framework_pkId");

                    b.HasOne("ProjectManagementSystem.Models.Language", "Language")
                        .WithMany("Projects")
                        .HasForeignKey("Language_pkId");

                    b.HasOne("ProjectManagementSystem.Models.ProjectType", "ProjectType")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectType_pkId");

                    b.HasOne("ProjectManagementSystem.Models.Student", "SubmittedByStudent")
                        .WithOne("SubmittedProject")
                        .HasForeignKey("ProjectManagementSystem.Models.Project", "SubmittedByStudent_pkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Framework");

                    b.Navigation("Language");

                    b.Navigation("ProjectType");

                    b.Navigation("SubmittedByStudent");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.ProjectFile", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.Project", "Project")
                        .WithMany("Files")
                        .HasForeignKey("Project_pkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.ProjectMember", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("Project_pkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagementSystem.Models.Student", "Student")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("Student_pkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Student", b =>
                {
                    b.HasOne("ProjectManagementSystem.Models.AcademicYear", "AcademicYear")
                        .WithMany("Students")
                        .HasForeignKey("AcademicYear_pkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagementSystem.Models.StudentDepartment", "StudentDepartment")
                        .WithMany("Students")
                        .HasForeignKey("Department_pkID");

                    b.HasOne("ProjectManagementSystem.Models.Email", "Email")
                        .WithMany("Students")
                        .HasForeignKey("Email_PkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectManagementSystem.Models.NRCType", "NRCType")
                        .WithMany()
                        .HasForeignKey("NRCType_pkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectManagementSystem.Models.NRCTownship", "NRCTownship")
                        .WithMany()
                        .HasForeignKey("NRC_pkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Email");

                    b.Navigation("NRCTownship");

                    b.Navigation("NRCType");

                    b.Navigation("StudentDepartment");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.AcademicYear", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.AdminActivityLog", b =>
                {
                    b.Navigation("Announcements");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.City", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Email", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Framework", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Language", b =>
                {
                    b.Navigation("Frameworks");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Project", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.ProjectType", b =>
                {
                    b.Navigation("Languages");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.Student", b =>
                {
                    b.Navigation("ProjectMembers");

                    b.Navigation("SubmittedProject");
                });

            modelBuilder.Entity("ProjectManagementSystem.Models.StudentDepartment", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
